name: Release + Publish

on:
  workflow_dispatch:
    inputs:
      versionChange:
        type: choice
        description: Select the version change
        required: true
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION_CHANGE: ${{ github.event.inputs.versionChange }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm

      - name: Install node_modules 📦
        run: npm ci

      - name: Update version ↗
        run: |
          git config --global user.name 'Rajeshwaran2001'
          git config --global user.email 'Rajeshwaran2001@users.noreply.github.com'
          git config --global push.followTags true
          npm version ${{ env.VERSION_CHANGE }} -m "Release %s"

      - name: Get meta data 🔍
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV
          echo "DISPLAY_NAME=$(node -p "require('./package.json').displayName")" >> $GITHUB_ENV

      - name: Build ⚒️
        run: npx --no-install vsce package

      - name: Push tags 📌
        run: git push

      - name: Release ${{ env.VERSION }} 🔆
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.NAME }}-${{ env.VERSION }}.vsix
          tag_name: v${{ env.VERSION }}
          name: ${{ env.DISPLAY_NAME }} v${{ env.VERSION }}
          generate_release_notes: true

      - name: Publish to Visual Studio Marketplace 🌐
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ env.NAME }}-${{ env.VERSION }}.vsix
